"""added template and extraction history

Revision ID: 17efa4f0c961
Revises: ad4a0dea6758
Create Date: 2025-11-23 23:32:06.836179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17efa4f0c961'
down_revision: Union[str, None] = 'ad4a0dea6758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
