"""add_password_reset_fields

Revision ID: 492f04e2df58
Revises: eb311f34dd13
Create Date: 2025-11-23 14:17:00.350226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '492f04e2df58'
down_revision: Union[str, None] = 'eb311f34dd13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('accounts', sa.Column('reset_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'reset_token_expires_at')
    op.drop_column('accounts', 'reset_token')
    # ### end Alembic commands ###
