"""Added connection status to channel

Revision ID: 84cc20673c10
Revises: 492f04e2df58
Create Date: 2025-11-23 20:59:02.431177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84cc20673c10'
down_revision: Union[str, None] = '492f04e2df58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('connected', sa.Boolean(), nullable=False))
    op.drop_column('channels', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('channels', 'connected')
    # ### end Alembic commands ###
