"""added rr to tp dictionary

Revision ID: dbcc3d0f6059
Revises: dff8fb5d550d
Create Date: 2025-11-24 10:51:21.344538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbcc3d0f6059'
down_revision: Union[str, None] = 'dff8fb5d550d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'risk_reward_ratio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('risk_reward_ratio', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
