"""Added connection status to channel

Revision ID: e392cada755b
Revises: 84cc20673c10
Create Date: 2025-11-23 21:16:25.662623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e392cada755b'
down_revision: Union[str, None] = '84cc20673c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('connection_status', sa.String(length=20), nullable=False))
    op.add_column('channels', sa.Column('connection_error', sa.Text(), nullable=True))
    op.drop_column('channels', 'connected')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('connected', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('channels', 'connection_error')
    op.drop_column('channels', 'connection_status')
    # ### end Alembic commands ###
