"""Added last active timestamp

Revision ID: e5426f92c5b0
Revises: e392cada755b
Create Date: 2025-11-23 21:22:42.853937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5426f92c5b0'
down_revision: Union[str, None] = 'e392cada755b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'last_active_at')
    # ### end Alembic commands ###
