"""added email field

Revision ID: eb311f34dd13
Revises: f17be418e772
Create Date: 2025-11-23 14:14:12.869040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb311f34dd13'
down_revision: Union[str, None] = 'f17be418e772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('email', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'accounts', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'email')
    # ### end Alembic commands ###
