"""accepts null for account non required fields

Revision ID: fdb431c5de1b
Revises: 2b2b7a6bcd19
Create Date: 2025-11-22 22:35:11.659763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdb431c5de1b'
down_revision: Union[str, None] = '2b2b7a6bcd19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'account_balance',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=True)
    op.alter_column('accounts', 'risk_per_trade',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('accounts', 'max_drawdown',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('accounts', 'telegram_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('accounts', 'mt5_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'mt5_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('accounts', 'telegram_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('accounts', 'max_drawdown',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('accounts', 'risk_per_trade',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('accounts', 'account_balance',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               nullable=False)
    # ### end Alembic commands ###
